# Bind server use ldaps:// for TLS
LdapServer: ldaps://10.1.1.1:636
LdapServer2: ldap://10.1.1.1

# Disable TLS verify false=disabled true=enabled
LdapTLSVerify: false
LdapTLSVerify2: false

# Bind to query usernames and groups
BindDN: cn=LDAP Bind User,cn=Users,dc=ad,dc=local
BindPassword: Pa55w0rd

# BaseDN for searching
SearchBase: cn=Users,dc=ad,dc=local

# Filter for account
# default (sAMAccountName=%s)
# auth only if member of group p_users (&(sAMAccountName=%s)(memberOf=CN=p_user,CN=Users,DC=ad,DC=local))
UserFilter: (sAMAccountName=%s)

# Filter for groups
# default (&(objectClass=group)(member=%s))
GroupFilter: (&(objectClass=group)(member=%s))

# Secret Key
SecretKey: supersecretkey

# Log to file
LogtoFile: false
LogFile: logs/mtauthserver.log

# GIN Debug mode
Debug: false
