version: '3'
services:
  go-mtauthserver:
    build:
      context: .
    image: mtauthserver
    container_name: mtauthserver
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml