definitions:
  mtauthserver.ResponseAuthError:
    properties:
      msg:
        type: string
      status:
        type: string
    type: object
  mtauthserver.ResponseError:
    properties:
      message:
        type: string
    type: object
  mtauthserver.ResponseToken:
    properties:
      exp:
        type: integer
      groups:
        items:
          type: string
        type: array
      status:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  mtauthserver.ResponseVerify:
    properties:
      app_name:
        type: string
      exp:
        type: integer
      groups:
        items:
          type: string
        type: array
      status:
        type: string
      username:
        type: string
    type: object
  mtauthserver.Token:
    properties:
      token:
        type: string
    type: object
  mtauthserver.UsernamePassword:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth:
    post:
      description: Authenticate to get JWT token
      parameters:
      - description: Username and Password
        in: body
        name: UsernamePassword
        required: true
        schema:
          $ref: '#/definitions/mtauthserver.UsernamePassword'
      produces:
      - application/json
      responses:
        "200":
          description: token response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseToken'
        "400":
          description: error response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseAuthError'
        "401":
          description: error response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseAuthError'
      summary: Authentication
  /introspect:
    post:
      description: Check JWT token
      parameters:
      - description: Token
        in: body
        name: Token
        required: true
        schema:
          $ref: '#/definitions/mtauthserver.Token'
      produces:
      - application/json
      responses:
        "200":
          description: verify response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseVerify'
        "400":
          description: error response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseAuthError'
        "401":
          description: error response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseAuthError'
      summary: Introspect
  /verify/{app_name}:
    get:
      description: Verify JWT token
      parameters:
      - description: application name
        in: path
        name: app_name
        required: true
        type: string
      - description: authentication token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: verify response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseVerify'
        "400":
          description: error response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseError'
        "401":
          description: error response
          schema:
            $ref: '#/definitions/mtauthserver.ResponseError'
      summary: Verification
swagger: "2.0"
