name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64, arm64]
        include:
          - goos: windows
            extension: .exe
        exclude:
          - goos: darwin
            goarch: arm64
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: myprogram-${{ matrix.goos }}-${{ matrix.goarch }}
        path: myprogram-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}
