name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    environment: default
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64, arm64]
        include:
          - goos: windows
            extension: .exe
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}
    - name: Upload Artifacts (temporary)
      uses: actions/upload-artifact@v2
      with:
        name: mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}
        path: mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}
          asset_name: mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}
          asset_content_type: application/octet-stream
