name: Go Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    environment: default
    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64, arm64]
        include:
          - goos: windows
            extension: .exe
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}
    - name: Upload Artifacts (temporary)
      uses: actions/upload-artifact@v2
      with:
        name: mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}
        path: mthauthserver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.extension || '' }}


  release:
    needs: build
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        with:
          gh-cli-version: 2.39.1
      - name: create github release
        run: |
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --notes-from-tag ./mthauthserver-*
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}

